import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

# change 54676

# change 16311

# change 10473

# change 71347

# change 96453

# change 35439

# change 68914

# change 32277

# change 18605

# change 6483

# change 18944

# change 13392

# change 68486

# change 45030

# change 52110

# change 11119

# change 75197

# change 36668

# change 44607

# change 79898

# change 47455

# change 4362

# change 71216

# change 32747

# change 7661

# change 33346

# change 19253

# change 9059

# change 70290

# change 73703

# change 40548

# change 70851

# change 15772

# change 27546

# change 39843

# change 89565

# change 84719

# change 79378

# change 39111

# change 43080

# change 84135

# change 51724

# change 25049

# change 26731

# change 93265

# change 60019

# change 25960

# change 4410

# change 48990
