# SearXNG settings

use_default_settings: true

server:
  secret_key: "370e48a5135cdf22a29ca63fb7c54b6eef1c1270782fcb06512c15a675b22349"
search:
  formats:
    - html
    - json
  # Safe search 0: off, 1: moderate, 2: strict
  safe_search: 0
  # List of engines to use
  engines:
    - name: google
      shortcut: g
    - name: duckduckgo
      shortcut: ddg
    - name: wikipedia
      shortcut: w

ui:
  static_use_hash: true

enabled_plugins:
  - 'Basic Plugins'
  - 'Hash plugin'
  - 'Self-contained'